version: '3.9'

services:
  postgres:
    container_name: postgres_posthub
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
  
  app_server:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
